name: Release

on:
  release:
    branches: [main]
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/setup-node@v2
        with:
          # minimum version supported by our dependencies (Jest)
          node-version: 14.15
          registry-url: https://npm.pkg.github.com
          scope: "@mo-id"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.name "GitHub Bot"
      - run: git config --global user.email "admin@moid.io"
      - run: npm run compile
      - run: npm test
      - run: npm run build
      - run: npm version --force ${{ github.event.release.tag_name }}
      - run: npm publish --tag ${{ github.event.release.target_commitish }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
